import { useEffect, useRef, useState } from 'react';
import { ArrowUpRight, ArrowRight, ArrowDown, Menu, X, Plus, Minus, Phone, MapPin, ShoppingBag, Search, ChevronLeft, ChevronRight } from 'lucide-react';
import { MENU_ITEMS, RESTAURANT_INFO as info } from './data/restaurantData';
import type { MenuItem } from './types';

const categories = [['asador','From the grill'],['tacos','Tacos & antojitos'],['especialidades','House specialties'],['cantina','Cantina'],['guarniciones','On the side'],['postres','Something sweet']];
const descriptions = ['Bone-in pork chop, charred onions, jalapeño, beans and tortillas.','Carne asada, chorizo, grilled chicken, nopal and queso asado. Made to share.','Skirt steak with poblano peppers, a cheese enchilada, guacamole and beans.','Cross-cut beef short ribs with oregano and chimichurri.','Citrus-marinated grilled chicken with onion, beans and rice.','Ribeye, cilantro, onion, avocado crema and salsa in three tortillas.','Smoked brisket, pickled red onions, cotija and chile salsa.','Melted cheese, chorizo and roasted poblano, with warm tortillas.','Masa cakes with barbacoa, beans, cabbage, crema and cotija.','Crisp chicken taquitos with salsa verde, crema and avocado.','Chicken enchiladas with mole, sesame seeds and onion.','Shrimp with garlic, guajillo, lime and cilantro rice.','Cheese enchiladas with ancho sauce, lettuce, radishes and crema.','A selection of lime, mango, hibiscus and prickly pear margaritas.','Tequila, lime, agave and orange liqueur.','Mezcal, hibiscus, lime and agave.','Mango, habanero tequila, lime and a Tajín rim.','Tequila, fresh lime and sparkling mineral water.','Pinto beans with bacon, chorizo, tomatoes and serrano.','Avocado, onion, cilantro, serrano and lime, with tostadas.','A dozen corn or flour tortillas.','Three-milk sponge cake with cream, cinnamon and berries.','Cinnamon-sugar churros with cajeta and chocolate.'];
const dishes = MENU_ITEMS.map((item,i)=>({...item,name:item.name.replace(/The Famous |Famous |Heirloom /g,''),description:descriptions[i]}));
const photos = [{src:'/images/grill.webp',title:'Around the fire',alt:'Grilled meat and vegetables on a sharing platter'},{src:'/images/tacos.webp',title:'A little lime. A little heat.',alt:'Tacos with fresh garnishes and lime'},{src:'/images/platter.webp',title:'Made for the middle of the table',alt:'A platter of grilled meat with vegetables'},{src:'/images/dining.webp',title:'The gathering mood',alt:'Warmly lit dining room, an illustrative mood photograph'}];
type Choice = {id:string; name:string; price:number; option:string; note:string; quantity:number};
type Panel = 'reserve'|'cart'|'dish'|'gallery'|'catering'|null;
const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n);
function Brand(){return <><span className="brand-name">EL ASADOR<small>MARGARITA RANCH GRILL</small></span></>}

export default function App(){
 const [navOpen,setNavOpen]=useState(false),[category,setCategory]=useState('asador'),[query,setQuery]=useState(''),[panel,setPanel]=useState<Panel>(null),[selected,setSelected]=useState<MenuItem>(dishes[0]),[option,setOption]=useState(''),[note,setNote]=useState(''),[photo,setPhoto]=useState(0),[cart,setCart]=useState<Choice[]>([]),[message,setMessage]=useState(''),[copied,setCopied]=useState(false);
 const dialog=useRef<HTMLDialogElement>(null);
 const count=cart.reduce((sum,x)=>sum+x.quantity,0),subtotal=cart.reduce((sum,x)=>sum+x.price*x.quantity,0);
 const visible=dishes.filter(x=>(query?true:x.category===category)&&((x.name+' '+x.description).toLowerCase().includes(query.toLowerCase())));
 useEffect(()=>{const el=dialog.current;if(!el||!panel)return;const previous=document.activeElement as HTMLElement;el.showModal();document.body.style.overflow='hidden';return()=>{el.close();document.body.style.overflow='';previous?.focus()}},[panel]);
 useEffect(()=>{if(!navOpen)return;const close=(e:KeyboardEvent)=>{if(e.key==='Escape'){setNavOpen(false);document.getElementById('nav-toggle')?.focus()}};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close)},[navOpen]);
 useEffect(()=>{if(!message)return;const timer=setTimeout(()=>setMessage(''),3500);return()=>clearTimeout(timer)},[message]);
 function choose(dish:MenuItem){setSelected(dish);setOption(dish.options?.[0]||'');setNote('');setPanel('dish')}
 function add(){const key=selected.id+'|'+option+'|'+note.trim();setCart(prev=>prev.some(x=>x.id===key)?prev.map(x=>x.id===key?{...x,quantity:x.quantity+1}:x):[...prev,{id:key,name:selected.name,price:selected.price,option,note:note.trim(),quantity:1}]);setCopied(false);setPanel(null);setMessage('Added to your pickup list. Call to place your order.')}
 function quantity(id:string,delta:number){setCart(prev=>prev.map(x=>x.id===id?{...x,quantity:x.quantity+delta}:x).filter(x=>x.quantity>0));setCopied(false)}
 async function copyList(){try{await navigator.clipboard.writeText(cart.map(x=>x.quantity+' × '+x.name+(x.option?' — '+x.option:'')+(x.note?' ('+x.note+')':'')).join('\n')+'\nEstimated subtotal: '+money(subtotal)+'\nPlease confirm prices and availability.');setCopied(true)}catch{setMessage('Copy is unavailable here. Your list is displayed for your call.')}}
 const closeNav=()=>setNavOpen(false);
 return <>
 <a className="skip-link" href="#main">Skip to content</a>
 <header className="site-header"><a href="#home" className="brand" aria-label="El Asador home" onClick={closeNav}><Brand/></a>
 <nav aria-label="Main navigation" className={navOpen?'main-nav expanded':'main-nav'} id="main-nav"><a href="#menu" onClick={closeNav}>The menu</a><a href="#story" onClick={closeNav}>Our story</a><a href="#experience" onClick={closeNav}>The experience</a><a href="#visit" onClick={closeNav}>Find us</a></nav>
 <div className="header-actions"><button className="bag-button" aria-label={'Pickup list, '+count+' items'} onClick={()=>setPanel('cart')}><ShoppingBag size={20}/><span>{count}</span></button><button className="button small header-book" onClick={()=>setPanel('reserve')}>Plan a visit <ArrowUpRight size={16}/></button><button className="nav-toggle" id="nav-toggle" aria-label={navOpen?'Close navigation':'Open navigation'} aria-expanded={navOpen} aria-controls="main-nav" onClick={()=>setNavOpen(!navOpen)}>{navOpen?<X/>:<Menu/>}</button></div></header>
 <main id="main">
 <section className="hero" id="home" aria-labelledby="hero-title"><img className="hero-image" srcSet="/images/grill-mobile.webp 800w, /images/grill.webp 1800w" sizes="100vw" src="/images/grill.webp" alt="Grilled meat and vegetables on a sharing platter, illustrative photography" fetchPriority="high" width="1800" height="1200"/><div className="hero-shade"/>
 <div className="hero-content"><p className="eyebrow light"><span/> EAST AUSTIN, TEXAS <span/></p><h1 id="hero-title">Good food.<br/><em>Great company.</em><br/>A little fire.</h1><p className="hero-description">Tamaulipas-style barbecue.<br/>A gathering place on East 7th Street.</p><div className="hero-buttons"><a className="button" href="#menu">Explore the menu <ArrowUpRight size={18}/></a><button className="button outline-button" onClick={()=>setPanel('reserve')}>Reservations & visits</button></div></div>
 <div className="hero-bottom"><span>EL ASADOR · MARGARITA RANCH GRILL</span><a href="#signatures">PULL UP A CHAIR <ArrowDown size={17}/></a><span>2617 E 7TH ST, AUSTIN</span></div></section>
 <div className="ribbon"><span>DEL ASADOR A TU MESA</span><span aria-hidden="true">✳</span><span>FROM THE GRILL TO YOUR TABLE</span><span aria-hidden="true">✳</span><span>EAST AUSTIN, TEXAS</span></div>
 <section className="section signatures" id="signatures"><div className="section-heading"><div><p className="eyebrow">01 / A TASTE OF EL ASADOR</p><h2>Start with<br/><em>something smoky.</em></h2></div><div className="heading-aside"><p>Big platters, tacos, and a reason<br/>to order something for the table.</p><a className="text-link" href="#menu">See the full menu <ArrowUpRight size={18}/></a></div></div>
 <div className="signature-grid">{[dishes[1],dishes[5],dishes[0]].map((dish,i)=><article className="signature-card" key={dish.id}><button className="dish-photo" aria-label={'View '+dish.name} onClick={()=>choose(dish)}><img src={['/images/grill.webp','/images/tacos.webp','/images/platter.webp'][i]} alt={['Grilled meat and vegetables','Tacos with fresh garnishes','Grilled meat platter'][i]} width="900" height="700" loading="lazy"/><span className="photo-number">0{i+1}</span><span className="photo-action"><ArrowUpRight/></span></button><div className="dish-title"><h3>{['Parrillada Ranchera','Tacos al Carbón','Tomahawk al Mezquite'][i]}</h3><span>{money(dish.price)}</span></div><p>{dish.description}</p></article>)}</div><p className="caption">Illustrative food photography. Menu and prices carried over from the previous website; please confirm when ordering.</p></section>
 <section className="story section" id="story"><div className="story-title"><p className="eyebrow">02 / ROOTED IN THE ASADOR</p><h2>Mexican soul.<br/><em>Austin spirit.</em></h2></div><div className="story-copy"><p className="large-copy">There’s something about a meal gathered around the grill.</p><p>El Asador Margarita Ranch Grill brings Tamaulipas-style barbecue to East Austin. The name puts the asador—the grill—at the heart of the table.</p><p>Find us on East 7th Street. Bring your appetite, choose something to share, and make a little time for good company.</p><a className="text-link" href="#visit">Come find us <ArrowUpRight size={18}/></a></div></section>
 <section className="menu-section section" id="menu"><div className="section-heading"><div><p className="eyebrow">03 / BUEN PROVECHO</p><h2>Find your<br/><em>next favorite.</em></h2></div><p className="menu-intro">Browse the menu and build a pickup list.<br/>Call the restaurant to confirm and order.</p></div><div className="menu-controls"><div className="category-list" aria-label="Menu categories">{categories.map(([id,label])=><button key={id} aria-pressed={category===id&&!query} onClick={()=>{setCategory(id);setQuery('')}}>{label}</button>)}</div><label className="search"><Search size={18}/><span className="sr-only">Search menu</span><input type="search" placeholder="Search the menu" value={query} onChange={e=>setQuery(e.target.value)}/></label></div>
 <div className="menu-list" aria-live="polite">{visible.map(dish=><article className="menu-item" key={dish.id}><div><h3>{dish.name}</h3><p>{dish.description}</p></div><div className="menu-price"><span>{money(dish.price)}</span><button aria-label={'Add '+dish.name+' to pickup list'} onClick={()=>choose(dish)}><Plus size={19}/></button></div></article>)}{visible.length===0&&<div className="empty"><h3>No dishes found.</h3><p>Try “tacos”, “chicken” or another ingredient.</p><button className="text-link" onClick={()=>setQuery('')}>Clear search</button></div>}</div><div className="menu-foot"><p>Prices and availability need restaurant confirmation. Ask the team about allergens and dietary requirements.</p><button className="text-link" onClick={()=>setPanel('cart')}>Your pickup list ({count}) <ArrowRight size={18}/></button></div></section>
 <section className="experience" id="experience"><div className="experience-photo"><img src="/images/dining.webp" alt="Dining room used as an atmosphere reference, not the El Asador interior" loading="lazy" width="1200" height="900"/><span>ATMOSPHERE INSPIRATION · STOCK PHOTOGRAPHY</span></div><div className="experience-copy"><p className="eyebrow light">04 / STAY A LITTLE LONGER</p><h2>For the food.<br/><em>For the company.</em></h2><p>A catch-up, a family meal, or a whole-table occasion. Let a meal at El Asador be the reason to get together.</p><p>Planning a group visit? Speak with the restaurant about seating, accessibility and availability before you come.</p><button className="button cream" onClick={()=>setPanel('reserve')}>Plan your visit <ArrowUpRight size={18}/></button><button className="text-link light-link" onClick={()=>setPanel('catering')}>Groups & catering enquiries <ArrowUpRight size={18}/></button></div></section>
 <section className="section gallery-section" id="gallery"><div className="section-heading"><div><p className="eyebrow">05 / A LITTLE APPETITE INSPIRATION</p><h2>Fire. Flavor. <em>Feeling.</em></h2></div><p className="heading-aside">Explore the gallery.<br/>A visual taste of the grill.</p></div><div className="gallery-grid">{photos.map((p,i)=><button key={p.src} onClick={()=>{setPhoto(i);setPanel('gallery')}} aria-label={'Open photo: '+p.title}><img src={p.src} alt={p.alt} loading="lazy" width="800" height="700"/><span>{p.title}<Plus size={18}/></span></button>)}</div><p className="caption">Stock imagery from Unsplash, retained as visual inspiration. Actual dishes and venue may differ.</p></section>
 <section className="visit section" id="visit"><div className="visit-intro"><p className="eyebrow">06 / YOUR TABLE STARTS HERE</p><h2>Come hungry.<br/><em>Find us on 7th.</em></h2><address>{info.address}<br/>{info.city}, {info.state} {info.zip}</address><a className="button" href={info.googleMapsUrl} target="_blank" rel="noreferrer">Get directions <ArrowUpRight size={18}/></a><a className="phone-link" href={'tel:'+info.rawPhone}><Phone size={17}/>{info.phone}</a></div><div className="hours"><h3>Make time for a good meal.</h3><p className="caption">Hours listed in the previous website · Austin / Central Time<br/>Please call to confirm before travelling.</p><dl>{info.hours.map(h=><div key={h.day}><dt>{h.day}</dt><dd>{h.time}</dd></div>)}</dl></div><div className="visit-note"><MapPin size={26}/><h3>East Austin,<br/>through and through.</h3><p>2617 East 7th Street.<br/>Open the map for your route.</p><a className="text-link" href={info.googleMapsUrl} target="_blank" rel="noreferrer">Open Google Maps <ArrowUpRight size={18}/></a><hr/><p>Reservations, pickup, large parties or a quick question?</p><button className="text-link" onClick={()=>setPanel('reserve')}>Talk to the restaurant <ArrowRight size={18}/></button></div></section>
 </main><footer><div className="footer-top"><a href="#home" className="brand"><Brand/></a><p>Good food brings us together.</p><a href="#home" className="text-link">Back to top <ArrowUpRight size={18}/></a></div><div className="footer-bottom"><span>© {new Date().getFullYear()} El Asador Margarita Ranch Grill</span><nav aria-label="Footer navigation"><a href="#menu">Menu</a><a href="#visit">Hours & contact</a><a href="#gallery">Gallery</a></nav><span>AUSTIN, TEXAS</span></div></footer>
 <div className="mobile-actions"><a href="#menu">View menu</a><button onClick={()=>setPanel('reserve')}>Plan a visit <ArrowUpRight size={17}/></button></div><div className="toast" role="status">{message}</div>
 <dialog ref={dialog} className={panel==='gallery'?'modal photo-modal':'modal'} aria-labelledby="dialog-title" onCancel={()=>setPanel(null)} onClick={e=>{const r=e.currentTarget.getBoundingClientRect();if(e.target===e.currentTarget&&(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom))setPanel(null)}} onKeyDown={e=>{if(panel==='gallery'&&(e.key==='ArrowRight'||e.key==='ArrowLeft')){e.preventDefault();setPhoto(i=>(i+(e.key==='ArrowRight'?1:photos.length-1))%photos.length)}}}><button className="close-modal" aria-label="Close dialog" onClick={()=>setPanel(null)}><X/></button>
 {(panel==='reserve'||panel==='catering')&&<><p className="eyebrow">LET’S GET TOGETHER</p><h2 id="dialog-title">{panel==='catering'?'Bring your people.':'Pull up a chair.'}</h2><p>{panel==='catering'?'Call to ask about group visits, catering options and availability.':'Call the restaurant to ask about reservations, seating and today’s hours.'}</p><div className="call-card"><Phone/><a href={'tel:'+info.rawPhone}>{info.phone}</a><span>{info.fullAddress}</span></div><a className="button" href={'tel:'+info.rawPhone}>Call the restaurant <ArrowUpRight size={18}/></a><p className="caption">This website does not confirm reservations or send enquiries. Arrangements are confirmed directly with the restaurant. Contact details are carried over from the previous website.</p><a className="text-link" href={info.googleMapsUrl} target="_blank" rel="noreferrer">Check the restaurant listing <ArrowUpRight size={16}/></a></>}
 {panel==='dish'&&<><p className="eyebrow">ADD TO YOUR PICKUP LIST</p><h2 id="dialog-title">{selected.name}</h2><p>{selected.description}</p><form onSubmit={e=>{e.preventDefault();add()}}>{selected.options&&<label className="field">Your preference<select value={option} onChange={e=>setOption(e.target.value)}>{selected.options.map(o=><option key={o}>{o}</option>)}</select></label>}<label className="field">Notes for your call <span className="caption">Optional</span><textarea maxLength={250} value={note} onChange={e=>setNote(e.target.value)} placeholder="Any preferences to discuss with the team?"/></label><button className="button" type="submit">Add to list · {money(selected.price)} <Plus size={18}/></button></form><p className="caption">This saves a list on this page only. No order is sent. Confirm availability, prices and allergens by phone.</p></>}
 {panel==='cart'&&<><p className="eyebrow">GOOD THINGS TO TAKE HOME</p><h2 id="dialog-title">Your pickup list.</h2>{cart.length===0?<div className="empty"><ShoppingBag size={36}/><p>Your list is waiting for something delicious.</p><a className="button" href="#menu" onClick={()=>setPanel(null)}>Explore the menu <ArrowRight size={18}/></a></div>:<><p>Your list is ready for a phone call. It has not been sent to the restaurant.</p><div className="cart-items">{cart.map(x=><div className="cart-item" key={x.id}><h3>{x.name}</h3><p>{x.option}{x.note?' · '+x.note:''}</p><div className="cart-row"><div className="quantity"><button aria-label={'Decrease '+x.name} onClick={()=>quantity(x.id,-1)}><Minus size={16}/></button><span>{x.quantity}</span><button aria-label={'Increase '+x.name} onClick={()=>quantity(x.id,1)}><Plus size={16}/></button></div><span>{money(x.price*x.quantity)}</span><button className="remove" onClick={()=>{setCart(prev=>prev.filter(y=>y.id!==x.id));setCopied(false)}}>Remove<span className="sr-only"> {x.name}</span></button></div></div>)}</div><div className="subtotal"><span>Estimated subtotal</span><strong>{money(subtotal)}</strong></div><p className="caption">Before taxes or fees. Final pricing and pickup time must be confirmed by the restaurant.</p><div className="dialog-actions"><a className="button" href={'tel:'+info.rawPhone}>Call to order <Phone size={18}/></a><button className="button secondary" onClick={copyList}>{copied?'List copied':'Copy my list'}</button></div><p className="caption">{info.phone} · Your list resets when you reload this page.</p></>}</>}
 {panel==='gallery'&&<><h2 id="dialog-title" className="sr-only">{photos[photo].title}</h2><img className="lightbox-image" src={photos[photo].src} alt={photos[photo].alt}/><div className="gallery-caption"><button aria-label="Previous photo" onClick={()=>setPhoto((photo+photos.length-1)%photos.length)}><ChevronLeft/></button><div><strong>{photos[photo].title}</strong><p>{photo+1} / {photos.length} · Illustrative stock photography</p></div><button aria-label="Next photo" onClick={()=>setPhoto((photo+1)%photos.length)}><ChevronRight/></button></div></>}
 </dialog></>;
}

